{
    'name': 'Product Create/Write Restriction',
    'version': '16.0.0.0.0',
    'category': 'product',
    'summery': '',
    'author': 'Atheer Global Solutions',
    'company': 'Atheer Global Solutions',
    'maintainer': 'Global Solutions',
    'website': 'https://www.atheerit.com',
    "license": "LGPL-3",
    'depends': ['product','base'],
    'data': [
        'security/group.xml',
        # 'views/product_template_view.xml',
        # 'views/product_product_view.xml',
    ],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
}
