# -*- coding: utf-8 -*-
{
    'name': 'Project Custom',
    'version': '14.0.20.0.8',
    'author': 'Atheer Global Solutions',
    'company': 'Atheer Global Solutions',
    'website': 'https://www.atheerit.com',
    "sequence": 1,
    'depends': ['hr_timesheet', 'report_xlsx', 'hr_holidays',
                'web_gantt', 'account_budget', 'timesheet_grid', 'project',
                'purchase', 'stock', ],
    # 'atr_hr_custom'
    'data': [
        'data/sequence.xml',
        'data/ir_cron.xml',
        'data/data.xml',
        'data/activity.xml',
        'security/project_security.xml',
        'security/ir.model.access.csv',
        'wizard/project_contract_renew.xml',
        'views/res_groups.xml',
        'views/project_view.xml',
        'views/project_menus.xml',
        'views/project_tender.xml',
        'wizard/manpower_status_wizard.xml',
        'wizard/sub_contract_report.xml',
        'wizard/project_receivable_report.xml',
        'wizard/project_payable_report.xml',
        'views/templates.xml',
        'report/report.xml',
        'report/report_layout.xml',
        'report/manpower_status_report.xml',
        'report/project_day_sheet.xml',
        'report/project_work_slip.xml',
        'wizard/tender_lost_reason.xml',
        'report/tender_report.xml',
        'report/project_tender_report_template.xml',
    ],
    'installable': True,
    'auto_install': False,
}
