# -*- coding: utf-8 -*-
{
    'name': 'Property Lease Management',
    'version': '16.0.1.7.7',
    'category': 'Property Management',
    'sequence': 1,
    'summary': 'Property, Landlord, Contract, Rent, Sale',
    'description': """
                    Real Estate Management
                    """,
    'author': 'Atheer Global Solutions',
    'website': 'https://www.atheerit.com',
    'depends': ['mail', 'account', 'hr', 'sign', 'report_xlsx', 'account_asset', 'atheer_documents', 'helpdesk',
                'project', 'crm', 'purchase', 'sale_crm'],
    'data': [
        # Security
        'security/security.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',

        # Data
        'data/ir_cron.xml',
        'data/asset_types.xml',
        'data/property_sequence.xml',
        'data/report_paperformat.xml',
        'data/building_area.xml',
        'data/property_types.xml',
        'data/data.xml',
        'data/vacating_information.xml',
        'data/bill_type.xml',
        'data/ir_actions_server.xml',
        'data/mail_data.xml',
        'data/mail_template.xml',

        # Views
        'views/property_view.xml',
        'views/property_maintenance_view.xml',
        'views/rent_view.xml',
        'views/partner_view.xml',
        'views/customer_issue.xml',
        'views/report.xml',
        'views/property_checklist.xml',
        'views/account_view.xml',
        'views/res_config_settings.xml',
        'views/tenant_request.xml',
        'views/monthly_bill.xml',
        # 'views/client_information.xml',
        # 'views/atheer_documents.xml',
        'views/res_partner_bank_views.xml',
        'views/tenant_rent_history.xml',
        'views/property_bounced_cheque.xml',
        'views/dispute_cheque_bounce.xml',
        'views/dispute_legal_action.xml',
        'views/project_task_views.xml',
        'views/vacating_information.xml',
        'views/all_property_maintenance.xml',
        'views/purchase_complaints_views.xml',
        'views/property_plot_views.xml',
        'views/unit_views.xml',
        'views/crm_lead_views.xml',
        'views/building_amenities_views.xml',
        'views/unit_floor_views.xml',

        # 'report/report_client_information.xml',
        'report/income_and_lost_opportunity_report.xml',
        'report/rent_payment_policy.xml',
        'report/repair_policy.xml',
        'report/key_turn_over.xml',
        'report/turnover_punchlist.xml',
        'report/monthly_bill_report.xml',
        'report/maintenance_report.xml',
        'report/work_completion_report.xml',
        'report/vacating_information_report.xml',
        'report/property_forcasting_report.xml',
        'report/tenant_renewal_commercial.xml',
        'report/tenant_renewal_sanad.xml',

        # Wizard
        'wizard/cost_of_opportunity_wizard.xml',
        'wizard/scheduled_work_completion_wizard.xml',
        'wizard/property_forcasting_excel_wizard.xml',
        'report/report_mrs_sheet.xml',
        'report/report_srs_sheet.xml',
        'report/repair_policy_notice.xml',
        'report/cancellation_form.xml',
        'wizard/maintenance_confirm.xml',
        'wizard/maintenance_attachment.xml',
        'wizard/security_deposit_wizard_views.xml',
        # 'wizard/monthly_approval_bill_wizard_views.xml',
    ],
    'demo': [],
    'test': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
