{
    'name': "Atheer Fleet",
    'version': '16.0.0.3.9',
    'license': 'LGPL-3',
    'author': "Atheer IT",
    'category': 'fleet',
    'depends': ['base', 'fleet', 'product', 'account', 'atheer_documents','analytic'],
    'description': """ """,
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/sequence.xml',
        'views/fuel_card_master.xml',
        'views/insurance_master.xml',
        'views/vehicle_master.xml',
        'views/number_plate_master.xml',
        'views/battery_master.xml',
        'views/vehicle_tyres_master.xml',
        'views/vehicle_inspection.xml',
        'views/service_entry.xml',
        'views/fuel_consumption.xml',
        'views/accident_details.xml',
        'views/fleet_request.xml',
        'views/insurance_types_views.xml',
        'views/vehicle_log_contract_views.xml',
    ],
}
