# -*- coding: utf-8 -*-
{
    'name': "Portfolio",
    'version': "16.0.2.0.1",
    'category': 'Purchases,Accounting,Sale',
    'author': 'Atheer Global Solutions',
    'company': 'Atheer Global Solutions',
    'summary': 'This module helps to handle share management.',
    'description': 'This module helps to handle shares in sales,purchases and dividends',
    'maintainer': 'Global Solutions',
    'website': 'https://www.atheerit.com',
    'depends': ['contacts','account','account_accountant','stock'],
    'data': [
        'security/portfolio_security_groups.xml',
        'security/ir.model.access.csv',
        'data/portfolio_purchase_sequence.xml',
        'data/adjustment_method_data.xml',
        'views/investment_views.xml',
        'views/investment_broker_views.xml',
        'views/sector_views.xml',
        'views/investor_views.xml',
        'views/investment_type_views.xml',
        'views/transaction_purchase_views.xml',
        'views/transaction_sale_views.xml',
        'views/market_exchange_views.xml',
        'views/transaction_dividend_views.xml',
        'views/investment_company_views.xml',
        'views/share_quant_views.xml',
        'views/investment_exchange_views.xml',
        'views/investment_market_views.xml',
        'views/investment_adjustment_views.xml',
        'views/account_move_views.xml',
        'views/adjustment_method_views.xml',


    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
