from . import vehicle_master
from . import number_plate_master
from . import battery_master
from . import fuel_card_master
from . import insurance_master
from . import vehicle_tyres_master
from . import vehicle_inspection
from . import service_entry
from . import fuel_card_entry
from . import accident_details
from . import fleet_request
from . import vehicle_log_contract
